### PR TITLE
Change confirmation email from hola@datos.gob.mx to participa@gob.mx Closes #81

### LINKED ISSUE #81: El mail de confirmación de registro hola@datos.gob.mx sugerimos cambiar a participa@gob.mx como más adecuado, o lo más cercano a eso...

### PR DESCRIPTION
**Pull request by codemoe**
Notice that the mail domain changed so it is necessary to verify that the change from @datos.gob.mx to @gob.mx can be done and function properly.

To test this change you can go through the sign up process or the password recovery process

### CODE REVIEW

**Comment by rodowi** [comment]
Esperando a conseguir el correo...

**Comment by rodowi** [comment]
El correo final será buzon@participa.gob.mx

cc: @urkonn

**Comment by codemoe** [comment]
@rodowi 

Realizado el cambio del mail....

cc: @urkonn

**Comment by urkonn** [comment]
selection_089

@rodowi

**Pull request merged**
