### PR TITLE
Fix/accessibility

### LINKED ISSUE #227: [Severe] An element's ID must be unique in the DOM
[Severe] An element's ID must be unique in the DOM (2)
https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_html_02
```html
<form role="form" id="subscribe" novalidate="" class="ng-pristine ng-valid">
<button class="blue-right btn" id="subscribe" type="button" ng-click="subscribeEmail()">
```

### LINKED ISSUE #228: [Severe] Controls and media elements should have labels
[Severe] Controls and media elements should have labels (5)
https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_text_01
```html
<input id="doc-text-filter" type="text" ng-model="docSearch" class="form-control ng-pristine ng-valid" placeholder="Título">
<input class="select2-focusser select2-offscreen" type="text" id="s2id_autogen1">
<input class="select2-focusser select2-offscreen" type="text" id="s2id_autogen2">
<input class="form-control ng-pristine ng-valid ng-valid-email" id="email" placeholder="Ingresa tu correo electrónico" type="email" ng-model="user">
<button class="blue-right btn" id="subscribe" type="button" ng-click="subscribeEmail()">

### LINKED ISSUE #229: [Warning] Meaningful images should not be used in element backgrounds (4)
https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_image_01
```html
<b></b>
<b></b>
<a class="social-icon facebook" href="https://www.facebook.com/PresidenciaMX"></a>
<a class="social-icon twitter" href="https://twitter.com/PresidenciaMX"></a>
```

### LINKED ISSUE #233: [Warning] Images should have a text alternative or presentational role (1)
/consulta/docs/manifesto-para-la-gobernanza-de-internet

[Warning] Images should have a text alternative or presentational role (1)
https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_text_02
```html
<img src="http://www.gob.mx/consulta-public/img/como-comentar.gif" class="how-to-annotate-img img-responsive">
```

### LINKED ISSUE #234: [Warning] The web page should have the content's human language indicated in the markup (2)
/participa

https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_html_01

```html
<html><head>...</html>
```html

### PR DESCRIPTION
**Pull request by codemoe**
Controls and media elements should have labels. Resolves #228
An element's ID must be unique in the DOM. Changed subscribe form button id. Resolves #227
Meaningful images should not be used in element backgrounds. Changed social icons implementation from background images to :before pseudo element content. Resolves #229
Images should have a text alternative or presentational role. Added alt attribute to how to participate gif on each doc layout. Resolves #233
Changed html lang attribute on main blade. The web page should have the content's human language indicated in the markup. Resolves #234

### CODE REVIEW

**Comment by rodowi** [comment]
#228, #229 siguen pendiente en /consulta

screen shot 2015-10-19 at 6 01 15 pm

**Comment by rodowi** [comment]
Algo se rompió en la vista de documentos (la parte de comments)

screen shot 2015-10-19 at 6 23 11 pm

**Comment by rodowi** [comment]
En /auth/login sigue el #227 

```html
<input class="form-control" id="email" type="text" name="email" value="" placeholder="Correo electrónico">
<input class="form-control ng-pristine ng-valid ng-valid-email" id="email" placeholder="Ingresa tu correo electrónico" type="email" ng-model="user">
```

**Comment by codemoe** [comment]
@rodowi Ya estuve revisando los errores faltantes y creo que ya quedaron solucionados todos a excepción de [Warning] Text elements should have a reasonable contrast ratio (50) y [Warning] The purpose of each link should be clear from the link text (6) para los elementos del paginator que habíamos comentado y [Warning] These elements are focusable but either invisible or obscured by another element (17)

**Comment by rodowi** [comment]
Se arregló el tema de los comentarios

screen shot 2015-10-20 at 10 08 01 pm

**Comment by rodowi** [comment]
:+1: se cubren bastantes

Los marqué en https://github.com/mxabierto/participa/issues/226

**Pull request merged**
